//
// PublicOutletAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BulkResponse<T: Codable>: Codable {
  
  public var count: Int
  public var rows: [T]
  
  public init(count: Int, rows: [T]) {
    self.count = count
    self.rows = rows
  }
  
  public enum CodingKeys: String, CodingKey, CaseIterable {
    case count
    case rows
  }
  
  // Encodable protocol methods
  
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(count, forKey: .count)
    try container.encode(rows, forKey: .rows)
  }
}

