//
// CategoryAttributesAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CategoryAttributesAllOf: Codable, JSONEncodable, Hashable {

    /** mdi icon for this string * */
    public var icon: String
    /** display name of this category */
    public var displayName: String
    /** type of this category */
    public var name: String

    public init(icon: String, displayName: String, name: String) {
        self.icon = icon
        self.displayName = displayName
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case icon
        case displayName
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(icon, forKey: .icon)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(name, forKey: .name)
    }
}

