//
// InternalError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InternalError: Codable, JSONEncodable, Hashable {

    public var name: String
    public var message: String
    public var stack: String?
    public var code: Double? = 6969

    public init(name: String, message: String, stack: String? = nil, code: Double? = 6969) {
        self.name = name
        self.message = message
        self.stack = stack
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case message
        case stack
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(stack, forKey: .stack)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

