//
// LoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginResponse: Codable, JSONEncodable, Hashable {

    public var token: JwtTokenResponse
    public var userId: Double

    public init(token: JwtTokenResponse, userId: Double) {
        self.token = token
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(userId, forKey: .userId)
    }
}

