//
// PartialRegistrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Make all properties in T optional */
public struct PartialRegistrationRequest: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var eth2Address: String?
    public var otp: String?
    public var phone: String?
    public var thirdParty: ThirdPartyAuth?
    public var userId: Double?
    public var username: String?
    public var thirdPartyGoogle: String?
    public var eth2SignedMessage: String?
    public var password: String?

    public init(email: String? = nil, eth2Address: String? = nil, otp: String? = nil, phone: String? = nil, thirdParty: ThirdPartyAuth? = nil, userId: Double? = nil, username: String? = nil, thirdPartyGoogle: String? = nil, eth2SignedMessage: String? = nil, password: String? = nil) {
        self.email = email
        self.eth2Address = eth2Address
        self.otp = otp
        self.phone = phone
        self.thirdParty = thirdParty
        self.userId = userId
        self.username = username
        self.thirdPartyGoogle = thirdPartyGoogle
        self.eth2SignedMessage = eth2SignedMessage
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case eth2Address
        case otp
        case phone
        case thirdParty
        case userId
        case username
        case thirdPartyGoogle = "thirdParty/google"
        case eth2SignedMessage
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(eth2Address, forKey: .eth2Address)
        try container.encodeIfPresent(otp, forKey: .otp)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(thirdParty, forKey: .thirdParty)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(thirdPartyGoogle, forKey: .thirdPartyGoogle)
        try container.encodeIfPresent(eth2SignedMessage, forKey: .eth2SignedMessage)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

