//
// PickSummaryAttributesExcludeKeyofSummaryAttributesRawTextOrFilteredText.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** From T, pick a set of properties whose keys are in the union K */
public struct PublicTranslationAttributes: Codable, Hashable {

  public var attribute: String
  public var value: String

  public init(attribute: String, value: String) {
    self.attribute = attribute
    self.value = value
  }

  public enum CodingKeys: String, CodingKey, CaseIterable {
    case attribute
    case value
  }

  // Encodable protocol methods

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(attribute, forKey: .attribute)
    try container.encode(value, forKey: .value)
  }
}

