//
// ReadingFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ReadingFormat: String, Codable, CaseIterable {
  case bullets = "bullets"
  case summary = "summary"
}
