//
// StatusAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StatusAttributes: Codable, JSONEncodable, Hashable {

    public var deletedAt: Date?
    public var updatedAt: Date?
    public var createdAt: Date?
    public var id: Double
    /** Construct a type with a set of properties K of type T */
    public var data: AnyCodable?
    public var description: String
    public var name: String

    public init(deletedAt: Date? = nil, updatedAt: Date? = nil, createdAt: Date? = nil, id: Double, data: AnyCodable? = nil, description: String, name: String) {
        self.deletedAt = deletedAt
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.id = id
        self.data = data
        self.description = description
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deletedAt
        case updatedAt
        case createdAt
        case id
        case data
        case description
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encode(description, forKey: .description)
        try container.encode(name, forKey: .name)
    }
}

