//
// StatusAttributesAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StatusAttributesAllOf: Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var data: AnyCodable?
    public var description: String
    public var name: String

    public init(data: AnyCodable? = nil, description: String, name: String) {
        self.data = data
        self.description = description
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case description
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encode(description, forKey: .description)
        try container.encode(name, forKey: .name)
    }
}

