//
// SubscriptionCreationAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionCreationAttributes: Codable, JSONEncodable, Hashable {

    public var newsletterName: String?
    public var newsletterId: Double?
    public var alias: String
    public var aliasType: String

    public init(newsletterName: String? = nil, newsletterId: Double? = nil, alias: String, aliasType: String) {
        self.newsletterName = newsletterName
        self.newsletterId = newsletterId
        self.alias = alias
        self.aliasType = aliasType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newsletterName
        case newsletterId
        case alias
        case aliasType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(newsletterName, forKey: .newsletterName)
        try container.encodeIfPresent(newsletterId, forKey: .newsletterId)
        try container.encode(alias, forKey: .alias)
        try container.encode(aliasType, forKey: .aliasType)
    }
}

