//
// VerifyOTPResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyOTPResponse: Codable, JSONEncodable, Hashable {

    public var userId: Double
    public var token: JwtTokenResponse

    public init(userId: Double, token: JwtTokenResponse) {
        self.userId = userId
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(token, forKey: .token)
    }
}

