import React from 'react';
import { Image, Linking } from 'react-native';

import ReactMarkdown from 'react-markdown';

import {
  Button,
  Divider,
  Text,
  View,
} from '~/components';
import { useStyles } from '~/hooks';

type Props = Omit<React.ComponentProps<typeof View>, 'children'> & {
  children: string;
  textStyles?: Omit<React.ComponentProps<typeof Text>['style'], 'children'>;
};

export function Markdown({ 
  children, 
  textStyles,
  ...props
}: Props) {
  const style = useStyles(props);
  return (
    <View style={ style }>
      <ReactMarkdown
        components={ { 
          a: (props) => (
            <Button onPress={ () => props.href && Linking.openURL(props.href) }>
              <Text { ...textStyles } underline>{props.children}</Text>
            </Button>
          ),
          abbr: (props) => <Text { ...textStyles }>{props.children}</Text>,
          address: (props) => <Text { ...textStyles }>{props.children}</Text>,
          animate: (props) => <Text { ...textStyles }>{props.children}</Text>,
          animateMotion: (props) => <Text { ...textStyles }>{props.children}</Text>,
          animateTransform: (props) => <Text { ...textStyles }>{props.children}</Text>,
          area: (props) => <Text { ...textStyles }>{props.children}</Text>,
          article: (props) => <Text { ...textStyles }>{props.children}</Text>,
          aside: (props) => <Text { ...textStyles }>{props.children}</Text>,
          audio: (props) => <Text { ...textStyles }>{props.children}</Text>,
          b: (props) => <Text { ...textStyles } bold>{props.children}</Text>,
          base: (props) => <Text { ...textStyles }>{props.children}</Text>,
          bdi: (props) => <Text { ...textStyles }>{props.children}</Text>,
          bdo: (props) => <Text { ...textStyles }>{props.children}</Text>,
          big: (props) => <Text { ...textStyles }>{props.children}</Text>,
          blockquote: (props) => <Text { ...textStyles }>{props.children}</Text>,
          body: (props) => <Text { ...textStyles }>{props.children}</Text>,
          br: (props) => <Text { ...textStyles }>{props.children}</Text>,
          button: (props) => <Text { ...textStyles }>{props.children}</Text>,
          canvas: (props) => <Text { ...textStyles }>{props.children}</Text>,
          caption: (props) => <Text { ...textStyles }>{props.children}</Text>,
          center: (props) => <Text { ...textStyles }>{props.children}</Text>,
          circle: (props) => <Text { ...textStyles }>{props.children}</Text>,
          cite: (props) => <Text { ...textStyles }>{props.children}</Text>,
          clipPath: (props) => <Text { ...textStyles }>{props.children}</Text>,
          code: (props) => <Text { ...textStyles } code>{props.children}</Text>,
          col: (props) => <Text { ...textStyles }>{props.children}</Text>,
          colgroup: (props) => <Text { ...textStyles }>{props.children}</Text>,
          data: (props) => <Text { ...textStyles }>{props.children}</Text>,
          datalist: (props) => <Text { ...textStyles }>{props.children}</Text>,
          dd: (props) => <Text { ...textStyles }>{props.children}</Text>,
          defs: (props) => <Text { ...textStyles }>{props.children}</Text>,
          del: (props) => <Text { ...textStyles }>{props.children}</Text>,
          desc: (props) => <Text { ...textStyles }>{props.children}</Text>,
          details: (props) => <Text { ...textStyles }>{props.children}</Text>,
          dfn: (props) => <Text { ...textStyles }>{props.children}</Text>,
          dialog: (props) => <Text { ...textStyles }>{props.children}</Text>,
          div: (props) => <Text { ...textStyles }>{props.children}</Text>,
          dl: (props) => <Text { ...textStyles }>{props.children}</Text>,
          dt: (props) => <Text { ...textStyles }>{props.children}</Text>,
          ellipse: (props) => <Text { ...textStyles }>{props.children}</Text>,
          em: (props) => <Text { ...textStyles } italic>{props.children}</Text>,
          embed: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feBlend: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feColorMatrix: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feComponentTransfer: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feComposite: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feConvolveMatrix: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feDiffuseLighting: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feDisplacementMap: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feDistantLight: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feDropShadow: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feFlood: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feFuncA: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feFuncB: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feFuncG: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feFuncR: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feGaussianBlur: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feImage: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feMerge: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feMergeNode: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feMorphology: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feOffset: (props) => <Text { ...textStyles }>{props.children}</Text>,
          fePointLight: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feSpecularLighting: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feSpotLight: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feTile: (props) => <Text { ...textStyles }>{props.children}</Text>,
          feTurbulence: (props) => <Text { ...textStyles }>{props.children}</Text>,
          fieldset: (props) => <Text { ...textStyles }>{props.children}</Text>,
          figcaption: (props) => <Text { ...textStyles }>{props.children}</Text>,
          figure: (props) => <Text { ...textStyles }>{props.children}</Text>,
          filter: (props) => <Text { ...textStyles }>{props.children}</Text>,
          footer: (props) => <Text { ...textStyles }>{props.children}</Text>,
          foreignObject: (props) => <Text { ...textStyles }>{props.children}</Text>,
          form: (props) => <Text { ...textStyles }>{props.children}</Text>,
          g: (props) => <Text { ...textStyles }>{props.children}</Text>,
          h1: (props) => <Text { ...textStyles } h1>{props.children}</Text>,
          h2: (props) => <Text { ...textStyles } h2>{props.children}</Text>,
          h3: (props) => <Text { ...textStyles } h3>{props.children}</Text>,
          h4: (props) => <Text { ...textStyles } h4>{props.children}</Text>,
          h5: (props) => <Text { ...textStyles } h5>{props.children}</Text>,
          h6: (props) => <Text { ...textStyles } h6>{props.children}</Text>,
          head: (props) => <Text { ...textStyles }>{props.children}</Text>,
          header: (props) => <Text { ...textStyles }>{props.children}</Text>,
          hgroup: (props) => <Text { ...textStyles }>{props.children}</Text>,
          hr: () => <Divider />,
          html: (props) => <Text { ...textStyles }>{props.children}</Text>,
          i: (props) => <Text { ...textStyles } italic>{props.children}</Text>,
          iframe: (props) => <Text { ...textStyles }>{props.children}</Text>,
          image: (props) => <Text { ...textStyles }>{props.children}</Text>,
          img: (props) => (
            <Image
              source={ { uri: props.src } }
              style={ {
                alignSelf: 'center', aspectRatio: 1,  
                resizeMode: 'contain', width: props.width ?? '100%',
              } } />
          ),
          input: (props) => <Text { ...textStyles }>{props.children}</Text>,
          ins: (props) => <Text { ...textStyles }>{props.children}</Text>,
          kbd: (props) => <Text { ...textStyles }>{props.children}</Text>,
          keygen: (props) => <Text { ...textStyles }>{props.children}</Text>,
          label: (props) => <Text { ...textStyles }>{props.children}</Text>,
          legend: (props) => <Text { ...textStyles }>{props.children}</Text>,
          li: (props) => <Text { ...textStyles }>{` • ${props.children}`}</Text>,
          line: (props) => <Text { ...textStyles }>{props.children}</Text>,
          linearGradient: (props) => <Text { ...textStyles }>{props.children}</Text>,
          link: (props) => <Text { ...textStyles }>{props.children}</Text>,
          main: (props) => <Text { ...textStyles }>{props.children}</Text>,
          map: (props) => <Text { ...textStyles }>{props.children}</Text>,
          mark: (props) => <Text { ...textStyles }>{props.children}</Text>,
          marker: (props) => <Text { ...textStyles }>{props.children}</Text>,
          mask: (props) => <Text { ...textStyles }>{props.children}</Text>,
          menu: (props) => <Text { ...textStyles }>{props.children}</Text>,
          menuitem: (props) => <Text { ...textStyles }>{props.children}</Text>,
          meta: (props) => <Text { ...textStyles }>{props.children}</Text>,
          metadata: (props) => <Text { ...textStyles }>{props.children}</Text>,
          meter: (props) => <Text { ...textStyles }>{props.children}</Text>,
          mpath: (props) => <Text { ...textStyles }>{props.children}</Text>,
          nav: (props) => <Text { ...textStyles }>{props.children}</Text>,
          noindex: (props) => <Text { ...textStyles }>{props.children}</Text>,
          noscript: (props) => <Text { ...textStyles }>{props.children}</Text>,
          object: (props) => <Text { ...textStyles }>{props.children}</Text>,
          ol: (props) => <Text { ...textStyles }>{props.children}</Text>,
          optgroup: (props) => <Text { ...textStyles }>{props.children}</Text>,
          option: (props) => <Text { ...textStyles }>{props.children}</Text>,
          output: (props) => <Text { ...textStyles }>{props.children}</Text>, 
          p: (props) => <Text { ...textStyles } mv={ 4 }>{props.children}</Text>,
          param: (props) => <Text { ...textStyles }>{props.children}</Text>, 
          path: (props) => <Text { ...textStyles }>{props.children}</Text>,
          pattern: (props) => <Text { ...textStyles }>{props.children}</Text>,
          picture: (props) => <Text { ...textStyles }>{props.children}</Text>,
          polygon: (props) => <Text { ...textStyles }>{props.children}</Text>,
          polyline: (props) => <Text { ...textStyles }>{props.children}</Text>,
          pre: (props) => <Text { ...textStyles } code>{props.children}</Text>,
          progress: (props) => <Text { ...textStyles }>{props.children}</Text>,
          q: (props) => <Text { ...textStyles }>{props.children}</Text>,
          radialGradient: (props) => <Text { ...textStyles }>{props.children}</Text>,
          rect: (props) => <Text { ...textStyles }>{props.children}</Text>,
          rp: (props) => <Text { ...textStyles }>{props.children}</Text>,
          rt: (props) => <Text { ...textStyles }>{props.children}</Text>,
          ruby: (props) => <Text { ...textStyles }>{props.children}</Text>,
          s: (props) => <Text { ...textStyles }>{props.children}</Text>,
          samp: (props) => <Text { ...textStyles }>{props.children}</Text>,
          script: (props) => <Text { ...textStyles }>{props.children}</Text>,
          section: (props) => <Text { ...textStyles }>{props.children}</Text>,
          select: (props) => <Text { ...textStyles }>{props.children}</Text>,
          slot: (props) => <Text { ...textStyles }>{props.children}</Text>,
          small: (props) => <Text { ...textStyles }>{props.children}</Text>,
          source: (props) => <Text { ...textStyles }>{props.children}</Text>,
          span: (props) => <Text { ...textStyles }>{props.children}</Text>,
          stop: (props) => <Text { ...textStyles }>{props.children}</Text>,
          strong: (props) => <Text { ...textStyles } bold>{props.children}</Text>,
          style: (props) => <Text { ...textStyles }>{props.children}</Text>,
          sub: (props) => <Text { ...textStyles }>{props.children}</Text>,
          summary: (props) => <Text { ...textStyles }>{props.children}</Text>,
          sup: (props) => <Text { ...textStyles }>{props.children}</Text>,
          svg: (props) => <Text { ...textStyles }>{props.children}</Text>,
          switch: (props) => <Text { ...textStyles }>{props.children}</Text>,
          symbol: (props) => <Text { ...textStyles }>{props.children}</Text>,
          table: (props) => <Text { ...textStyles }>{props.children}</Text>,
          tbody: (props) => <Text { ...textStyles }>{props.children}</Text>,
          td: (props) => <Text { ...textStyles }>{props.children}</Text>,
          template: (props) => <Text { ...textStyles }>{props.children}</Text>,
          text: (props) => <Text { ...textStyles }>{props.children}</Text>,
          textPath: (props) => <Text { ...textStyles }>{props.children}</Text>,
          textarea: (props) => <Text { ...textStyles }>{props.children}</Text>,
          tfoot: (props) => <Text { ...textStyles }>{props.children}</Text>,
          th: (props) => <Text { ...textStyles }>{props.children}</Text>,
          thead: (props) => <Text { ...textStyles }>{props.children}</Text>,
          time: (props) => <Text { ...textStyles }>{props.children}</Text>,
          title: (props) => <Text { ...textStyles }>{props.children}</Text>,
          tr: (props) => <Text { ...textStyles }>{props.children}</Text>,
          track: (props) => <Text { ...textStyles }>{props.children}</Text>,
          tspan: (props) => <Text { ...textStyles }>{props.children}</Text>,
          u: (props) => <Text { ...textStyles } underline>{props.children}</Text>,
          ul: (props) => <Text { ...textStyles }>{props.children}</Text>,
          use: (props) => <Text { ...textStyles }>{props.children}</Text>,
          'var': (props) => <Text { ...textStyles }>{props.children}</Text>,
          video: (props) => <Text { ...textStyles }>{props.children}</Text>,
          view: (props) => <Text { ...textStyles }>{props.children}</Text>,
          wbr: (props) => <Text { ...textStyles }>{props.children}</Text>,
          webview: (props) => <Text { ...textStyles }>{props.children}</Text>,
        } }
        skipHtml>
        {children}
      </ReactMarkdown>
    </View>
  );
}
