FROM node:19.3.0 as base
RUN npm install -g pnpm
WORKDIR /home/node/app
COPY package.json ./
COPY src ./src
RUN pnpm install

FROM base as pre-build
COPY tsconfig.json ./
COPY tsconfig.build.json ./

FROM pre-build as build
RUN pnpm run build:cron
# tiktoken hack 🙄
RUN cp $(for f in node_modules/.pnpm/@dqbd+tiktoken*; do echo $f; done | sort -r | xargs | awk '{print $1}')/node_modules/@dqbd/tiktoken/dist/node/_tiktoken_bg.wasm ./dist

FROM build as cron
CMD pnpm run start:cron