FROM node:19.3.0 as base
RUN npm install -g pnpm
WORKDIR /home/node/app
COPY package.json ./
COPY src ./src
RUN pnpm install

FROM base as pre-build
COPY tsconfig.json ./
COPY tsconfig.build.json ./

FROM pre-build as build
RUN pnpm run build:api
COPY deps/_tiktoken_bg.wasm ./dist

FROM build as api
CMD pnpm run start:api