FROM node:19.3.0 as base
WORKDIR /home/node
COPY src/server ./server
WORKDIR /home/node/server
RUN yarn install --non-interactive --frozen-lockfile
WORKDIR /home/node/app
COPY src/web/package.json ./
COPY src/web/yarn.lock ./
RUN yarn install --non-interactive --frozen-lockfile

FROM base as pre-build
COPY src/web/src ./src
COPY src/web/public ./public
COPY src/web/tsconfig.json ./
COPY src/web/config-overrides.js ./
RUN yarn swagger

FROM pre-build as build
ARG API_ENDPOINT
ENV API_ENDPOINT=${API_ENDPOINT}
ARG GENERATE_SOURCEMAP
ENV GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
RUN echo > .env
RUN echo API_ENDPOINT=\"${API_ENDPOINT}\" >> .env
RUN echo GENERATE_SOURCEMAP=\"${GENERATE_SOURCEMAP}\" >> .env
RUN echo GOOGLE_CLIENT_ID=\"${GOOGLE_CLIENT_ID}\" >> .env

ENV NODE_ENV=production
RUN yarn build

FROM nginx:alpine as web
COPY src/web/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /home/node/app/build /etc/nginx/html
