FROM node:19.3.0 AS base
WORKDIR /home/node/app
COPY src/server/package.json ./
COPY src/server/yarn.lock ./
COPY src/server/src ./src
RUN yarn install --non-interactive --immutable

FROM base AS dev
COPY src/server/tsconfig.json ./
COPY src/server/tsconfig.build.json ./
COPY src/server/serve-api.ts ./
COPY src/server/nodemon.api.json ./
RUN yarn cp:core
CMD yarn dev:applink