FROM node:19.3.0 AS base
WORKDIR /home/node
COPY src/core ./core
WORKDIR /home/node/app
COPY src/server/package.json ./
COPY src/server/yarn.lock ./
COPY src/server/src ./src
RUN yarn install --non-interactive --immutable

FROM base AS pre-build
COPY src/server/tsconfig.json ./
COPY src/server/tsconfig.build.json ./

FROM pre-build AS build
# swagger.json file
COPY src/server/tsoa.config.json ./
RUN yarn cp:core
RUN yarn tsoa
ENV NODE_ENV=production
RUN yarn build:applink
# tiktoken hack 🙄
RUN cp node_modules/@dqbd/tiktoken/dist/node/_tiktoken_bg.wasm ./dist

FROM build AS api
CMD yarn start:applink