FROM node:19.3.0 as base
WORKDIR /home/node/app
COPY src/server/package.json ./
COPY src/server/yarn.lock ./
COPY src/server/src ./src
RUN yarn install --non-interactive --immutable

FROM base as dev
COPY src/server/tsconfig.json ./
COPY src/server/tsconfig.build.json ./
COPY src/server/serve-worker.ts ./
COPY src/server/nodemon.worker.json ./
CMD yarn dev:worker