FROM node:19.3.0 as base
WORKDIR /home/node/app
COPY src/server/package.json ./
COPY src/server/yarn.lock ./
COPY src/server/src ./src
RUN yarn install --non-interactive --immutable

FROM base as pre-build
COPY src/server/tsconfig.json ./
COPY src/server/tsconfig.build.json ./

FROM pre-build as build
ENV NODE_ENV=production
RUN yarn build:worker
# tiktoken hack 🙄
RUN cp node_modules/@dqbd/tiktoken/dist/node/_tiktoken_bg.wasm ./dist

FROM build as worker
CMD yarn start:worker