FROM node:19.3.0 as base
RUN npm install -g pnpm
WORKDIR /home/node
COPY src/server ./server
WORKDIR /home/node/server
RUN pnpm install
WORKDIR /home/node/app
COPY src/web/package.json ./
RUN pnpm install

FROM base as pre-build
COPY src/web/src ./src
COPY src/web/public ./public
COPY src/web/tsconfig.json ./
COPY src/web/config-overrides.js ./
RUN pnpm run swagger

FROM pre-build as build
ARG API_ENDPOINT
ENV API_ENDPOINT=${API_ENDPOINT}
ARG GENERATE_SOURCEMAP
ENV GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
RUN echo > .env
RUN echo API_ENDPOINT=\"${API_ENDPOINT}\" >> .env
RUN echo GENERATE_SOURCEMAP=\"${GENERATE_SOURCEMAP}\" >> .env
RUN pnpm run build

FROM nginx:alpine as web
COPY src/web/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /home/node/app/build /etc/nginx/html
