FROM node:19.3.0 as base
RUN npm install -g pnpm
WORKDIR /home/node/app
COPY src/server/package.json ./
COPY src/server/src ./src
RUN pnpm install

FROM base as dev
COPY src/server/tsconfig.json ./
COPY src/server/tsconfig.build.json ./
COPY src/server/serve-cron.ts ./
COPY src/server/nodemon.cron.json ./
CMD pnpm dev:cron