//
// DatedAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DatedAttributes: Codable, JSONEncodable, Hashable {

    public var deletedAt: Date?
    public var updatedAt: Date?
    public var createdAt: Date?
    public var id: Double

    public init(deletedAt: Date? = nil, updatedAt: Date? = nil, createdAt: Date? = nil, id: Double) {
        self.deletedAt = deletedAt
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deletedAt
        case updatedAt
        case createdAt
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
    }
}

