//
// InteractionUserVote.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum InteractionUserVote: String, Codable, CaseIterable {
    case up = "up"
    case down = "down"
}
