//
// InteractionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InteractionRequest: Codable, JSONEncodable, Hashable {

    /** Construct a type with a set of properties K of type T */
    public var metadata: AnyCodable?
    public var content: String?
    public var remoteAddr: String?
    public var userId: Double?

    public init(metadata: AnyCodable? = nil, content: String? = nil, remoteAddr: String? = nil, userId: Double? = nil) {
        self.metadata = metadata
        self.content = content
        self.remoteAddr = remoteAddr
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metadata
        case content
        case remoteAddr
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(remoteAddr, forKey: .remoteAddr)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

