//
// LogoutResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LogoutResponse: Codable, JSONEncodable, Hashable {

    public var count: Double
    public var success: Bool

    public init(count: Double, success: Bool) {
        self.count = count
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(success, forKey: .success)
    }
}

