//
// PartialLogoutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Make all properties in T optional */
public struct PartialLogoutRequest: Codable, JSONEncodable, Hashable {

    public var userId: Double?
    public var token: String?
    public var force: Bool?

    public init(userId: Double? = nil, token: String? = nil, force: Bool? = nil) {
        self.userId = userId
        self.token = token
        self.force = force
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case token
        case force
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(force, forKey: .force)
    }
}

