//
// PublicOutletAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicOutletAttributes: Codable, Hashable {

    public var description: String?
    public var displayName: String
    public var name: String
    public var id: Double

    public init(description: String? = nil, displayName: String, name: String, id: Double) {
        self.description = description
        self.displayName = displayName
        self.name = name
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case displayName
        case name
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(name, forKey: .name)
        try container.encode(id, forKey: .id)
    }
}

