//
// ReadingFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ReadingFormat: String, Codable, CaseIterable {
  case bullets = "bullets"
  case casual = "casual"
  case concise = "concise"
  case detailed = "detailed"
  case inDepth = "in-depth"
}
