//
// ReleaseAttributesAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReleaseAttributesAllOf: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var version: String
    public var platform: Platform

    public init(description: String? = nil, version: String, platform: Platform) {
        self.description = description
        self.version = version
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case version
        case platform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(version, forKey: .version)
        try container.encode(platform, forKey: .platform)
    }
}

