//
// ReleaseAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReleaseAttributes: Codable, JSONEncodable, Hashable {

    public var deletedAt: Date?
    public var updatedAt: Date?
    public var createdAt: Date?
    public var id: Double
    public var description: String?
    public var version: String
    public var platform: Platform

    public init(deletedAt: Date? = nil, updatedAt: Date? = nil, createdAt: Date? = nil, id: Double, description: String? = nil, version: String, platform: Platform) {
        self.deletedAt = deletedAt
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.id = id
        self.description = description
        self.version = version
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deletedAt
        case updatedAt
        case createdAt
        case id
        case description
        case version
        case platform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(version, forKey: .version)
        try container.encode(platform, forKey: .platform)
    }
}

