//
// SubscriptionAttributesAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionAttributesAllOf: Codable, JSONEncodable, Hashable {

    public var newsletterId: Double
    public var alias: String
    public var aliasType: String

    public init(newsletterId: Double, alias: String, aliasType: String) {
        self.newsletterId = newsletterId
        self.alias = alias
        self.aliasType = aliasType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newsletterId
        case alias
        case aliasType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(newsletterId, forKey: .newsletterId)
        try container.encode(alias, forKey: .alias)
        try container.encode(aliasType, forKey: .aliasType)
    }
}

