//
// ThirdParty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ThirdParty: String, Codable, CaseIterable {
    case google = "google"
}
