export const VOICES = {
  Adrian: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'Adrian',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Adrian',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Adrian.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
  },
  Alexander: {
    accent: 'british',
    age: 'old',
    gender: 'male',
    id: 'Alexander',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Alexander',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Alexander.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
  },
  Anthony: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'Anthony',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Anthony',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Anthony.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'thick',
  },
  Aurora: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'Aurora',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Aurora',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Aurora.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'round',
  },
  Axel: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'Axel',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Axel',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Axel.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
  },
  Carter: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'Carter',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Carter',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Carter.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'thick',
  },
  Daisy: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'Daisy',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Daisy',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Daisy.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'gravelly',
  },
  Ellie: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'Ellie',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Ellie',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Ellie.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'smooth',
  },
  Evelyn: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'Evelyn',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Evelyn',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Evelyn.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'smooth',
  },
  Frankie: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'Frankie',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Frankie',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Frankie.wav',
    style: 'training',
    tempo: 'neutral',
    texture: 'thick',
  },
  Frederick: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'Frederick',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Frederick',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Frederick.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'thick',
  },
  Harrison: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'Harrison',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Harrison',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Harrison.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'round',
  },
  Hudson: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'Hudson',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Hudson',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Hudson.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'thick',
  },
  Hunter: {
    accent: 'british',
    age: 'old',
    gender: 'male',
    id: 'Hunter',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Hunter',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Hunter.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'round',
  },
  Julian: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'Julian',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Julian',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Julian.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'round',
  },
  Lillian: {
    accent: 'british',
    age: 'old',
    gender: 'female',
    id: 'Lillian',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Lillian',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Lillian.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'round',
  },
  Lottie: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'Lottie',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Lottie',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Lottie.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  Nolan: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'Nolan',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Nolan',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Nolan.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'round',
  },
  Nova: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'Nova',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'whisper',
    name: 'Nova',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Nova.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  Owen: {
    accent: 'american',
    age: 'youth',
    gender: 'male',
    id: 'Owen',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Owen',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Owen.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
  },
  Phoebe: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'Phoebe',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Phoebe',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Phoebe.wav',
    style: 'videos',
    tempo: 'fast',
    texture: 'smooth',
  },
  Stella: {
    accent: 'british',
    age: 'old',
    gender: 'female',
    id: 'Stella',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Stella',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Stella.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'round',
  },
  Theodore: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'Theodore',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Theodore',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/Theodore.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'gravelly',
  },
  abram: {
    accent: 'british',
    age: 'old',
    gender: 'male',
    id: 'abram',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Abram',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/abram.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'round',
  },
  adolfo: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'adolfo',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Adolfo',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/adolfo.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
  },
  ahmed: {
    accent: 'british',
    age: 'old',
    gender: 'male',
    id: 'ahmed',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Logan',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/ahmed.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'thick',
  },
  alex: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'alex',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Alex',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/alex.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'thick',
  },
  alfonso: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'alfonso',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Alfonso',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/alfonso.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'gravelly',
  },
  alphonso: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'alphonso',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Alphonso',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/alphonso.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'smooth',
  },
  amado: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'amado',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Amado',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/amado.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'smooth',
  },
  anny: {
    accent: 'american',
    age: 'youth',
    gender: 'female',
    id: 'anny',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Anny',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/anny.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'thick',
  },
  arthur: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'arthur',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Arthur',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/arthur.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  aubrey: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'aubrey',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Aubrey',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/aubrey.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'smooth',
  },
  benton: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'benton',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Benton',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/benton.wav',
    style: 'videos',
    tempo: 'fast',
    texture: 'smooth',
  },
  bertram: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'bertram',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Bertram',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/bertram.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'gravelly',
  },
  bill: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'bill',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Harper',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/bill.wav',
    style: 'videos',
    tempo: 'fast',
    texture: 'smooth',
  },
  blaine: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'blaine',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Blaine',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/blaine.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'thick',
  },
  booker: {
    accent: 'british',
    age: 'youth',
    gender: 'male',
    id: 'booker',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Booker',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/booker.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
  },
  bret: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'bret',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Bret',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/bret.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  bruce: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'bruce',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Bruce',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/bruce.wav',
    style: 'training',
    tempo: 'fast',
    texture: 'thick',
  },
  bryan: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'bryan',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Bryan',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/bryan.wav',
    style: 'videos',
    tempo: 'fast',
    texture: 'gravelly',
  },
  carlo: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'carlo',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Carlo',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/carlo.wav',
    style: 'advertising',
    tempo: 'neutral',
    texture: 'smooth',
  },
  charles: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'charles',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Charles',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/charles.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
  },
  charlotte: {
    accent: 'canadian',
    age: 'adult',
    gender: 'female',
    id: 'charlotte',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Charlotte',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/charlotte.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  chuck: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'chuck',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Chuck',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/chuck.wav',
    style: 'videos',
    tempo: 'slow',
    texture: 'round',
  },
  clark: {
    accent: 'british',
    age: 'old',
    gender: 'male',
    id: 'clark',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Clark',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/clark.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  clifton: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'clifton',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Clifton',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/clifton.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'gravelly',
  },
  dane: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'dane',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Dane',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/dane.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'round',
  },
  daniel: {
    accent: 'canadian',
    age: 'adult',
    gender: 'male',
    id: 'daniel',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Daniel',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/daniel_vo.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  darnell: {
    accent: 'american',
    age: 'youth',
    gender: 'male',
    id: 'darnell',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Darnell',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/darnell.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  daron: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'daron',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Daron',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/daron.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'round',
  },
  darrell: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'darrell',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Darrell',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/darrell.wav',
    style: 'advertising',
    tempo: 'neutral',
    texture: 'thick',
  },
  denis: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'denis',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Eleanor',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/denis.wav',
    style: 'advertising',
    tempo: 'neutral',
    texture: 'smooth',
  },
  dick: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'dick',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Dick',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/dick.wav',
    style: 'training',
    tempo: 'fast',
    texture: 'smooth',
  },
  domenic: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'domenic',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Domenic',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/domenic.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'thick',
  },
  donovan: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'donovan',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Donovan',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/donovan.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  dudley: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'dudley',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Dudley',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/dudley.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'smooth',
  },
  dylan: {
    accent: 'british',
    age: 'old',
    gender: 'male',
    id: 'dylan',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Dylan',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/dylan.wav',
    style: 'videos',
    tempo: 'slow',
    texture: 'smooth',
  },
  earle: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'earle',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Earle',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/earle.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'gravelly',
  },
  efren: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'efren',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Efren',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/efren.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'thick',
  },
  elijah: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'elijah',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Elijah',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/elijah.wav',
    style: 'training',
    tempo: 'neutral',
    texture: 'gravelly',
  },
  erasmo: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'erasmo',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Erasmo',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/erasmo.wav',
    style: 'training',
    tempo: 'fast',
    texture: 'smooth',
  },
  fletcher: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'fletcher',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Fletcher',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/fletcher.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'gravelly',
  },
  florencio: {
    accent: 'british',
    age: 'old',
    gender: 'female',
    id: 'florencio',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Madison',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/florencio.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'round',
  },
  flynn: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'flynn',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Flynn',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/flynn.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'round',
  },
  gabriel: {
    accent: 'american',
    age: 'old',
    gender: 'female',
    id: 'gabriel',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Samantha',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/gabriel.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'thick',
  },
  greg: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'greg',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Greg',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/greg.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'round',
  },
  harold: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'harold',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Harold',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/harold.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  harris: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'harris',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Harris',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/harris.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'smooth',
  },
  hayden: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'hayden',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Cooper',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/hayden.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
  },
  hipolito: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'hipolito',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Audrey',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/hipolito.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'round',
  },
  ignacio: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'ignacio',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Delilah',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/ignacio.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  jarrett: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'jarrett',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Jarrett',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/jarrett.wav',
    style: 'advertising',
    tempo: 'slow',
    texture: 'smooth',
  },
  jerrell: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'jerrell',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Jerrell',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/jerrell.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
  },
  jordan: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'jordan',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Jordan',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/jordan.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'round',
  },
  judson: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'judson',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Judson',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/judson.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  lance: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'lance',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Lance',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/lance.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'smooth',
  },
  larry: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'larry',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Larry',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/larry.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  lucius: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'lucius',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Lucius',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/lucius.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  micah: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'micah',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Micah',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/micah.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  mickey: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'mickey',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Madelyn',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/mickey.wav',
    style: 'videos',
    tempo: 'fast',
    texture: 'thick',
  },
  oliver: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'oliver',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Oliver',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/oliver.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'round',
  },
  oscar: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'oscar',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Oscar',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/oscar.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  pedro: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'pedro',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Pedro',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/pedro.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'round',
  },
  randall: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'randall',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Randall',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/randall.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
  },
  reynaldo: {
    accent: 'british',
    age: 'old',
    gender: 'male',
    id: 'reynaldo',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Reynaldo',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/reynaldo.wav',
    style: 'narrative',
    tempo: 'fast',
    texture: 'smooth',
  },
  rodrick: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'rodrick',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Rodrick',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/rodrick.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  samuel: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'samuel',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Samuel',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/samuel.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'gravelly',
  },
  spencer: {
    accent: 'british',
    age: 'adult',
    gender: 'female',
    id: 'spencer',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'April',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/spencer.wav',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
  },
  susan: {
    accent: 'american',
    age: 'adult',
    gender: 'female',
    id: 'susan',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Susan',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/susan.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'round',
  },
  victor: {
    accent: 'american',
    age: 'youth',
    gender: 'female',
    id: 'victor',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    name: 'Ariana',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/victor.wav',
    style: 'videos',
    tempo: 'fast',
    texture: 'thick',
  },
  wilbert: {
    accent: 'british',
    age: 'adult',
    gender: 'male',
    id: 'wilbert',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Wilbert',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/wilbert.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
  },
  wilbur: {
    accent: 'american',
    age: 'youth',
    gender: 'male',
    id: 'wilbur',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'Wilbur',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/wilbur.wav',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
  },
  wilfred: {
    accent: 'american',
    age: 'old',
    gender: 'male',
    id: 'wilfred',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    name: 'Wilfred',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/wilfred.wav',
    style: 'training',
    tempo: 'slow',
    texture: 'smooth',
  },
  william: {
    accent: 'american',
    age: 'adult',
    gender: 'male',
    id: 'william',
    is_cloned: false,
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    name: 'William',
    sample: 'https://peregrine-samples.s3.amazonaws.com/editor-samples/william_vo.wav',
    style: 'videos',
    tempo: 'neutral',
    texture: 'round',
  },
};
