FROM node:19.3.0 as base
RUN npm install -g pnpm
WORKDIR /home/node/app
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install

FROM base as pre-build
COPY src ./src
COPY public ./public
COPY tsconfig.json ./
COPY config-overrides.js ./
COPY swagger.json ./
COPY nodemon.json ./
COPY .env ./
RUN pnpm run gen

FROM pre-build as dev
CMD pnpm run dev